

module.exports.HTTP_RESPONSE = {
	SAVED_SUCCESS:"SAVED_SUCCESS",
	OBJECT_EXISTS:"OBJECT_EXISTS",
	SESSION_RESTORED:"SESSION_RESTORED",
	SESSION_CREATED:"SESSION_CREATED",
	INVALID_PASSWORD:"INVALID_PASSWORD",
	OBJECT_NOT_FOUND:"OBJECT_NOT_FOUND"
};

module.exports.WORD = {
	USER_EXISTS:"USER_EXISTS",
	USER_LOGIN_INVALID:"USER_LOGIN_INVALID",
	USER_SAVED:"USER_SAVED",
	FIELD_REQUIRED:"FIELD_REQUIRED",
	LENGTH_MIN_REQUIRED:"LENGTH_MIN_REQUIRED",
	LENGTH_MAX_REQUIRED:"LENGTH_MAX_REQUIRED"
};


module.exports.COMPARISION_OPERATOR = {
	eq	:'==',
	ne	:'!=',
	gt	:'>',
	lt	:'<',
	ge	:'>=',
	le	:'<='
};
